services:
  - type: web
    name: algorithm-visualizer
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Add this in the Render dashboard
      - key: PORT
        value: 10000
